= Introduction

The phrase "it doesn't matter, just be consistent" has really harmed the C++
community more than it has helped. "A foolish consistency," if you will.
Developers' desire to keep their codebase unique and "special" has held back
the development of tooling when every user insists that a tool support their
own custom style.

For some things, like where you put the opening brace, the difference might
truly be insignificant. For other things, this isn't the case.

One such thing is the layout of a project on a filesystem.

Incongruous layouts not only harms tooling, they create unnecessary disparity,
create friction during on-boarding of contributors, and present a huge burden to
beginners for a task that shouldn't even take more than a few seconds of
thought.

For virtually all projects, they are some (maybe improper) subset of a few key
components:

* Compilable source files
* Public headers
* Private headers
* Source files containing entry points (`main()` functions)
* Documentation files
* Tests
* Samples and examples
* External libraries which have been embedded within the project structure
* "Add-ons" to the source (e.g. language bindings, optional plugins, platform
bindings)

In addition, it is very common to see projects which subdivide themselves into
submodules. These submodules may also have dependencies between
each-other. Submodules greatly increase the complexity potential, but aren't
completely out of the question. A project layout standard _must_ be able to
handle subdivided projects.

== Background and Terminology

The ideas and concepts presented herein are not novel. Rather, they are built
upon the work of others. Some come from professional idea and experience, while
others come from community convention, which has gradually converged on to
prefer certain patterns while decrying others.

=== Physical vs. Logical Layout

This document builds heavily upon the work of John Lakos, who has spear-headed
much work on the aspects of _physical design_. Much work has been put into
evangelizing in the area of _logical design_, but _physical design_ to this day
remains a topic that (in this author's opinion) is too often overlooked when
designing and implementing systems, as well as the teaching thereof.

John Lakos's 1996 book _Large-Scale C++ Software Design_, to this day, remains
as _the_ book on _physical design_ in C++.

So what's the difference between _physical_ and _logical_ design?

*Logical design* pertains closely to programming-language-level aspects of the
design of a system.

*Physical design* pertains to the aspects of design _outside_ of what is
encoded by the language.

The source unit dealt with by the C and C++ standards is the _translation
unit_. This corresponds to a source file which has had all preprocessor
directives resolved. This is the closest that the language standards get to
discussing _physical design_ of systems.

Physical design, despite its name, still lives within the digital space, of
course. It concerns the placement and naming of files and directories within a
filesystem, as well as how to coordinate communication between physical units
where the relationship between their filesystem locations is not deterministic.

This document does not address much in the way of _logical design_. Rather, it
is specifically written to address many common questions and resolve common
answers for _physical design_.

=== The _Physical Component_

The most fundamental unit of _physical design_ is the *Component*.

A _component_ should correspond to exactly two files: A _header_ and a _source_
file. For some _rare_ cases it may be beneficial to use more than a single
source file in a single physical component, but it may be a sign that further
refactoring is needed.

Additionally, a component may have a test source file, but it is not considered
a part of the physical component.

=== Logical/Physical Coherence

This document assumes that developers will work to maintain logical/physical
_coherence_. There must be a coherent relationship between the logical and
physical components of a system, and a single logical component must not be
spread across multiple physical components. Multiple logical components should
not appear within the same physical component.

Note: _Logical components_ can include more than an individual class or
function. For example, it may include classes representing private data (for
the PIMPL pattern), or `friend` classes and functions. Blindly splitting every
class and function into individual physical components is not required nor
recommended.

Physical components must not form cyclic dependencies.

=== Packages, Projects, Modules, and Submodules

The terms defined in prior sections were heavily borrowed from John Lakos's
work. His work also often uses the term _package_ to refer to a collection of
source components. This would roughly correspond to the entire source
repository, including build files, support files, documentation, scripts, and
data.

Unfortunately, the term "package" has been heavily overloaded. These days,
"package" most often refers to a unit of distribution of software, rather than
the software itself. For this reason, this document prefers the term "project,"
and will use it instead of "package," although they mean the same thing.

In a similar vein, the term _module_ has also been heavily overloaded. In the
wake of upcoming C++ module specifications and implementations, the word
"module" will be avoided as to avoid ambiguity and confusion as a "module"
corresponds with neither a _package_/*project* nor a _physical component_.

Still, a term is needed to refer to the subdivisions of a large project into
smaller elements. For example, _Qt_ is an enormous framework of many
interconnected pieces. To refer to these pieces _Qt_ uses the term "module",
which has already been excluded.

For lack of a better unqualified term, the best this author can find is a
qualified term: _Submodule_. This term will be used to denote separate sections
of a project which can be consumed on as-needed basis.


== Project Files

PFL prescribes several files that should be present in the root of the project:

* A `README` file should be present. It should be easily readable in plaintext,
but may use "enhanced" plaintext like Markdown or similar. It should
contain a description of the contents of the directory and subdirectories.
* A `LICENSE` file must be present for projects that wish to redistribute
themselves. It must be plaintext (ie. not enhanced with markup).

Tool-support files, such as `.gitignore` and `.clang-format`, may be present in
this directory.

Other files in the root directory must be pertinent to the build system of the
project. Other files should not appear in the root of the project.

== Project Directories ##

PFL prescribes several directories that should appear at the root of the project
tree. Not all of the directories are required, but they have an assigned
purpose, and no other directory in the filesystem may assume the role of one of
these directories. That is, these directories must be the ones used if their
purpose is required.

Other directories should not appear at the root.

Note: If you have a need not fulfilled by a PFL directory listed below, that is a bug in this specification, and I would love to hear from you!
Before reporting, double-check that what you need isn't listed below and in the following sections.:
        
        
==== build/

A special directory that should not be considered part of the source of the
project. Used for storing ephemeral build results. must not be checked into
source control. If using source control, must be ignored using source
control ignore-lists.
        
        
      
      
[src/]
      :: Main compilable source location. must be present for projects with compiled
      components that do not use submodules.
      
      
      
      In the presence of link:./%23tld.include.html[include/], also contains private
      headers.
      
      
    
    
    link:./%23tld.include.html[include/]
    :: Directory for public headers. may be present. may be omitted for projects
    that do not distinguish between private/public headers. may be omitted for
    projects that use submodules.
    
    
  
  
  link:./%23tld.tests.html[tests/]
  :: Directory for tests.
  

link:./%23tld.examples.html[examples/]
:: Directory for samples and examples.

link:./%23tld.external.html[external/]
:: Directory for packages/projects to be used by the project, but not edited as
part of the project.

link:./%23tld.extras.html[extras/]
:: Directory containing extra/optional submodules for the project.

link:./%23tld.data.html[data/]
:: Directory containing non-source code aspects of the project. This might
include graphics and markup files.

link:./%23tld.tools.html[tools/]
:: Directory containing development utilities, such as build and refactoring
scripts

link:./%23tld.docs.html[docs/]
:: Directory for project documentation.

link:./%23tld.libs.html[libs/]
:: Directory for main project submodules.

= Top-Level Directories # {#tld}

Pitchfork specifies several top-level directories. Other directories should not
be present in the root directory, except for what is required by other tooling.

== `build/` ## {#tld.build}

This directory is not required, but its name should be reserved.

The `build/` directory is special in that it must not be committed to a source
control system. A user downloading the codebase should not see a `build/`
directory present in the project root, but one may be created in the course of
working with the software. The `_build/` directory is also reserved.

Note: Some build systems may commandeer the `build/` directory for themselves.
In this case, the directory `_build/` should be used in place of `build/`.

The `build/` directory may be used for ephemeral build results. Other uses of
the directory are not permitted.

Creation of additional directories for build results in the root directory is
not permitted.

Note: Although multiple _root_ directories are not allowed, the structure and
layout of the `build/` directory is not prescribed. Multiple subdirectories of
`build/` may be used to hold multiple build results of different configuration.

== `include/` ## {#tld.include}

Note: The `include/` and link:./%23tld.src.html[src/] directories are very closely
related. Be sure to also read its section in addition to this one.

The purpose of the `include/` directory is to hold _public API_ headers.

The `include/` directory should not be used if using
link:./%23src.header-placement.merged.html[#src.header-placement.merged].

See link:./%23src.html[#src].

== `src/` ## {#tld.src}

Note: The `src/` and link:./%23tld.include.html[include/] directories are very closely
related. Be sure to also read its section in addition to this one.

The purpose and content of `src/` depends on whether the project authors choose
to follow link:./%23src.header-placement.merged.html[#src.header-placement.merged] or
link:./%23src.header-placement.separate.html[#src.header-placement.separate].

See link:./%23src.html[#src].

== `tests/` ## {#tld.tests}

This directory is not required.

The `tests/` directory is reserved for source files related to (non-unit) tests
for the project.

The structure and layout of this directory is not prescribed by this document.

A project which can be embedded in another project (such as via
link:./%23tld.external.html[#tld.external]), must disable its `tests/` directory if it can detect that it
is being built as an embedded sub-project.

Project maintainers must provide a way for consumers to disable the compilation
and running of tests, especially for the purpose of embedding.

== `examples/` ## {#tld.examples}

This directory is not required.

The `examples/` directory is reserved for source files related to example and
sample usage of the project. The structure and layout of this directory is not
prescribed by this document.

Project maintainers must provide a way for consumers to disable the compilation
of examples and samples.

== `external/` ## {#tld.external}

This directory is not required.

The `external/` directory is reserved for embedding of external projects. Each
embedded project should occupy a single subdirectory of `external/`.

`external/` should not contain files other than those required by tooling.

This directory may be automatically populated, either partially or completely,
by tools (eg. `git` submodules) as part of a build process. In this case,
projects must declare the auto-populated subdirectories as ignored by relevant
source control systems.

Subdirectories of `external/` should not be modified as part of regular project
development. Subdirectories should remain as close to their upstream source as
possible.

== `data/` ## {#tld.data}

This directory is not required.

The `data/` directory is designated for holding project files which should be
included in revision control, but are not explicitly code. For example,
graphics and localization files are not code in the same sense as the rest of
the project, but are good candidates for inclusion in the `data/` directory.

The structure and layout of this directory is not prescribed by this document.

== `tools/` ## {#tld.tools}

This directory is not required.

The `tools/` directory is designated for holding extra scripts and tools related
to developing and contributing to the project. For example, turn-key build
scripts, linting scripts, code-generation scripts, test scripts, or other tools
that may be useful to a project develop.

The contents of this directory should not be relevant to a project consumer.

== `docs/` ## {#tld.docs}

This directory is not required.

The `docs/` directory is designated to contain project documentation. The
documentation process, tools, and layout is not prescribed by this document.

== `libs/` ## {#tld.libs}

The `libs/` directory must not be used unless the project wishes to subdivide
itself into link:./%23submod.html[submodules]. Its presence excludes the link:./%23tld.src.html[src/]
and link:./%23tld.include.html[include/] directories.

See link:./%23submod.html[#submod] and link:./%23submod.libs.html[#submod.libs].

== `extras/` ## {#tld.extras}

This directory is not required.

`extras/` is a link:./%23submod.root.html[submodule root]. See link:./%23submod.html[#submod] and
link:./%23submod.extras.html[#submod.extras].

= Library Source Layout # {#src}

A _library source tree_ refers to the layout of source code files that comprise
a single library, which is a collection of code that is exposed to the library's
_consumer_.

== Header File Placement ## {#src.header-placement}

This document supports two different methods of placing headers in a single
library: _separate_ and _merged_. These two methods are mutually exclusive
within a single library source tree.

=== Separate Header Placement ### {#src.header-placement.separate}

In _separated_ placement, there are two _source directories_, link:./%23tld.include.html[#tld.include]
and link:./%23tld.src.html[#tld.src]. The `include/` directory is designated to contain the _public_
headers of the library, while the _src/_ directory is designated to contain
the compilable source code and _private_ headers.

Note: Not all projects will necessarily have private headers.

In separate placement, a single physical component is split between the two
directories. The relative path to the parent directory of a compilable source
file in the `src/` directory must be equivalent to the relative path to the
parent directory of the header in the `include/` directory that corresponds to
the compilable source file.

Note: The purpose of the deterministic header/file path relationship is to aid
both tools and human viewers in understanding and manipulating the source
directory structure.

Note: The relative paths of these physical components is not arbitrary. See
link:./%23src.layout.html[#src.layout].

Consumers of a library using separated header layout should be given the path to
the link:./%23tld.include.html[#tld.include] directory as the sole include search directory for the
library's public interface. This prevents users from being able to `#include`
paths which exist only in the `src/` directory.

The library itself should be compiled with both its link:./%23tld.include.html[#tld.include] and
link:./%23tld.src.html[#tld.src] directories as include search directories. This ensures that the
library itself can access all files within both source directories.

=== Merged Header Placement ### {#src.header-placement.merged}

In _merged_ header placement, there is a single _source directory_,
link:./%23tld.src.html[#tld.src].

Much like with separated placement, the relative path from the source directory
to the parent of directory of the files of a physical component must be the
same. This implies that the files of a physical component will always be
_sibling_ files in the same directory.

== Test Placement ## {#src.tests}

This document distinguishes between _unit_ tests, and other tests. Unit tests
are tests that roughly correspond to a single single _unit_ of the source code.
This may be a physical component, public API, or combination thereof. The
distinguishing of a unit test has implications on where it may be placed.

=== Merged Test Placement ### {#src.tests.merged}

Optional but recommended is to use _merged_ test placement. In this method,
a unit test should have exactly one compilable source file, and that filename
stem should be the same as the filename stem of the physical component under
test, with a `.test` appended to it. For example, a test for the physical
component comprised of `meow.hpp` and `meow.cpp` will be named `meow.test.cpp`.
This unit test source file should be placed in the same directory as a
compilable source file of the physical component under test. Therefore, when
the unit has a compilable source file, the unit test source file will appear as
a sibling of the compilable source file.

=== Separate Test Placement ### {#src.tests.separate}

If not using merged tests, all tests should be placed within the
link:./%23tld.tests.html[tests/] top-level directory. There are no mandates on the layout
within `tests/`.

== Source Directory Layout ## {#src.layout}

For the purposes of this section, the link:./%23tld.include.html[include/] and
link:./%23tld.src.html[src/] top-level directories are both included in the definition of
"source directories." They are root of the _library source tree_. They are
named as such because they contain the primary "source files" of the source
language (C and/or C++).

No non-source-code files will should be placed _or generated_ in any
subdirectories of a source directory. That is, the root of a source directory
may contain non-source-code files, but no child directories should.

Conversely, no source-code files should be placed in the root of a source
directory. That is, all source files must have _qualified paths_ relative to the
root of their source directory.

Header files and source files should correspond to a logical component of the
project. For example, a `geometry` library might contain a `circle` class along
a single header and (optional) source file to represent it. If no other
logical components appear in that header and/or source file, the logical
component can be said to be the "main component" of the corresponding source
component. The main logical component may be a `class`, function, or some
grouping thereof.

The layout of the source tree should closely correspond to the namespace
structure of the project.

In C, there is no language-level concept of a namespace, but there is the
convention of qualifying globally visible identifiers with a "pseudo" namespace.
For example, a `libfoo` might define a `foo_create()`, where the prefix `foo_`
acts as the "namespace" for the identifier. The namespace for these purposes can
be said to be `foo`.

In C++, which has a language-level `namespace`, the need to qualify identifiers
in this way is not necessary (when using C++ linkage). Instead, these qualifiers
are put in `namespace`s.

Given that each logical component has a namespace, we can associate that
namespace with the physical component in which it is defined. This namespace
can then be used to generate a qualified path by which the physical component
can be found. In this way, physical components can be considered
"content-addressable".

Source files should be placed in a directory relative to the source
directory where the relative path is composed by joining the elements of the
component namespace as intermediate directories. The stem of the source filename
should correspond to the name of the logical component which it declares or
defines.

In some cases, it may be advantageous to separate the compiled source file into
multiple compiled source files while maintaining a single header file. In this
case, the stem of the source file should begin the same as if it were not
subdivided, then qualified with a `.` separating the distinguishing
characteristic of the source file.

= Submodules # {#submod}

Very large projects (eg. Qt, Boost, JUCE, LLVM) will benefit from the concept of::
_submodules_.::


===== Submodule
:: A subdivision of a larger project which can be consumed as-needed. Contains
its own source trees, tests, data, and documentation.


Note: Splitting a project into submodules should be considered _very carefully_.
It is an extremely heavy tool with subtleties that often trip people up. Very
few projects warrant subdividing themselves in this way.
Most projects will do just fine with multiple namespaces and directories within
their source tree. Don't reach for this tool when namespaces and subdirectories
will suite you just fine. Converting a project to/from a submodule layout is
a very cumbersome task.



The following rules must be taken into consideration when considering or using
submodules:


* *Submodules are not themselves standalone projects*.
* They should not pretend to be entire projects.
* They cannot be consumed independent of the rest of the project.
* They should not be versioned separately from the project.
* They _cannot_ further subdivide into sub-submodules.

== Submodule Root ## {#submod.root}



: Submodule Root
:: A directory whose child directories are link:./%23submod.dir.html[submodules].



Submodule roots include:


* link:./%23tld.extras.html[#tld.extras]
* link:./%23submod.libs.html[#submod.libs]

Each subdirectory of a submodule root must correspond to exactly one submodule.



== Submodule Directory ## {#submod.dir}



A submodule is represented as a subdirectory of the project which may contain
the following directories:


* link:./%23tld.src.html[src/] for submodule sources
* link:./%23tld.include.html[include/] for submodule includes (if splitting headers)
* link:./%23tld.tests.html[tests/] for submodule tests
* link:./%23tld.data.html[data/] for submodule data
* link:./%23tld.examples.html[examples/] for examples
* link:./%23tld.docs.html[docs/] for submodule documentation

Note: Most of the link:./%23tld.html[top-level directories] are _absent_ from this list.



Submodules directories should not contain other files or directories except
those required by tooling.



== `libs/` ## {#submod.libs}



The `libs/` directory is for _main_ submodules. It is a
link:./%23submod.root.html[submodule root].



When the `libs/` directory is present, the top-level `src/` and `include/`
directories must not be present. Instead of having a root source tree, a project
using `libs/` for submodules should instead refactor itself such that the
project has a common basis submodule upon which other submodules will may
depend.



The main difference between `libs/` and link:./%23tld.extras.html[extras/] is that the
`libs/` submodules found in `libs/` should be built _by default_, although a
consumer may opt-out of the submodules on an as-needed basis.



== `extras/` ## {#submod.extras}
  
  
  
The `extras/` directory is designated for containing additional submodules for
the project which build upon the main component(s). This may include submodules
that are not part of the project's "default" build, or otherwise impose special
requirements to be used.



For example, the following might be candidates for `extra/` rather than regular
components:


. "Language bindings" or extra libraries that provide integrations of the
project with programming languages or runtimes different from its own.
. "Platform bindings" or extra libraries (plugins) that integrate the project
with a particular platform. For example, a windowing library that needs to
understand how to talk with Windows, Quartz, X11, and Wayland would include
its platform integration implementations in this directory.
. "Contributed" submodules. Additional submodules that are contributed by the
project's users and included in upstream, but are not officially supported
by the project.
. Optional submodules that require additional dependencies, or may be
prohibitive to include for all users. For example, Qt's Webkit module is
prohibitively time consuming to build, and it requires the presence of
dependencies that are only required exactly for that one component.

= Build Systems # {#builds}



This document does not mandate any particular build system. The only
requirements is that the chosen build system support the layout herein defined.



= Libraries # {#libraries}



For library projects, a source tree should correspond to _exactly one_ library.
That is, _at most one one_ linkable result, and _exactly one_ public include
directory. A single `#include` tree must not require linking more than one
library to access all symbols exported from that tree.



Note: Submodules, having their own source tree, may each contain a library that
can be linked and consumed independently.



A single source tree should not vary its public interface based on anything
other than the target platform. This has several big implications, including
(but not limited to) the following:


* A library should not offer the user controls for tweaking its public
interface.
* A library should not change its public interface based on the
presence/absence of external software.
  
= Open Questions